name: Build images
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'Builder/node_modules/**'

env:
  TAG_NAME: 3.0.0-rc1-alpine
  USERNAME: mileszim

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build builder image
        working-directory: ./Builder
        run: docker build -t builder .

      - name: Build final image
        working-directory: ./Final
        run: docker build -t final .

      - name: Push the images to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

          # docker tag builder ghcr.io/${{ env.USERNAME }}/rails-base-builder:latest
          docker tag builder ghcr.io/${{ env.USERNAME }}/rails-base-builder:${{ env.TAG_NAME }}
          # docker push ghcr.io/${{ env.USERNAME }}/rails-base-builder:latest
          docker push ghcr.io/${{ env.USERNAME }}/rails-base-builder:${{ env.TAG_NAME }}

          # docker tag final ghcr.io/${{ env.USERNAME }}/rails-base-final:latest
          # docker push ghcr.io/${{ env.USERNAME }}/rails-base-final:latest
          docker tag final ghcr.io/${{ env.USERNAME }}/rails-base-final:${{ env.TAG_NAME }}
          docker push ghcr.io/${{ env.USERNAME }}/rails-base-final:${{ env.TAG_NAME }}

      - name: Push the images to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u mileszim --password-stdin

          # docker tag builder ${{ env.USERNAME }}/rails-base-builder:latest
          # docker push ${{ env.USERNAME }}/rails-base-builder:latest
          docker tag builder ${{ env.USERNAME }}/rails-base-builder:${{ env.TAG_NAME }}
          docker push ${{ env.USERNAME }}/rails-base-builder:${{ env.TAG_NAME }}

          # docker tag final ${{ env.USERNAME }}/rails-base-final:latest
          # docker push ${{ env.USERNAME }}/rails-base-final:latest
          docker tag final ${{ env.USERNAME }}/rails-base-final:${{ env.TAG_NAME }}
          docker push ${{ env.USERNAME }}/rails-base-final:${{ env.TAG_NAME }}
